### ISSUE TITLE
Update SSO proxy policy to further restrict access to dependencytrack SBOM endpoint

### ISSUE THREAD

**Issue by mohdnr** [cds-snc/security-tools#27]
Currently we're allowing unauthenticated `PUT` requests to the sbom endpoint. This is to facilitate sending SBOM files from our CI workflow into dependencytrack. I'd like to update our pomerium policy to further restrict the PUT to the api path that receives the sboms.

e.g.

```yml
  policy:
      - allow:
          and:
            - http_method:
                is: PUT
            - http_path:
                is: /foo/bar
```

docs: https://www.pomerium.com/enterprise/reference/manage.html#pomerium-policy-language
